version: "3.7"

networks:
  mariadb_net:

volumes:
  mariadb:

services:
  ### MariaDB ##############################################
  mariadb:
    image: mariadb:${MARIADB_TAG}
    volumes:
        - mariadb:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MARIADB_PORT}:3306"
    networks:
        - mariadb_net

  ### phpMyAdmin ###########################################
  phpmyadmin:
    image: phpmyadmin:${PHPMYADMIN_TAG}
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOST=mariadb
    ports:
    - "${PHPMYADMIN_LISTEN_PORT}:80"
    networks:
    - mariadb_net
