version: '3.7'

services:
  base:
    build:
      context: ./images/base
      dockerfile: Dockerfile
      args:
        - UBUNTU_RELEASE=${UBUNTU_RELEASE}
        - NON_ROOT_USER=${NON_ROOT_USER}
        - PUID=${PUID}
        - PGID=${PGID}
        - http_proxy
        - https_proxy
        - no_proxy
    image: ${COMPOSE_PROJECT_NAME}/base:ubuntu

  base-alpine:
    build:
      context: ./images/base
      dockerfile: Dockerfile.alpine
      args:
        - ALPINE_RELEASE=${ALPINE_RELEASE}
        - NON_ROOT_USER=${NON_ROOT_USER}
        - PUID=${PUID}
        - PGID=${PGID}
        - http_proxy
        - https_proxy
        - no_proxy
    image: ${COMPOSE_PROJECT_NAME}/base:alpine

  sandbox:
    build:
      context: ./images/vnc
      dockerfile: Dockerfile
      args:
        - DEVELOPSY_BASE_TAG=${DEVELOPSY_BASE_TAG}
        - VNC_PASS=${VNC_PASS}
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - base
    image: ${COMPOSE_PROJECT_NAME}/vnc:1.0-${UBUNTU_RELEASE}
    ports:
      - "5920:5920"

  base-android:
    build:
      context: ./images/base-android
      dockerfile: Dockerfile
      args:
        - JDK_VERSION=${JDK_VERSION}
        - GRADLE_VERSION=${GRADLE_VERSION}
        - VNC_TAG=${VNC_TAG}
        - SKD=${SKD}
        - http_proxy
        - https_proxy
        - no_proxy
    image: ${COMPOSE_PROJECT_NAME}/base-android:sdk

  android-emulator:
    build:
      context: ./images/android-emulator
      dockerfile: Dockerfile
      args:
        - ANDROID_API_LEVEL=${ANDROID_API_LEVEL}
        - ANDROID_IMAGE=${ANDROID_IMAGE}
        - ANDROID_BUILD_TOOLS_LEVEL=${ANDROID_BUILD_TOOLS_LEVEL}
        - EMULATOR_NAME=${EMULATOR_NAME}
        - ARCH=${ARCH}
        - http_proxy
        - https_proxy
        - no_proxy
    image: ${COMPOSE_PROJECT_NAME}/android-emulator:api${ANDROID_API_LEVEL}
    environment:
      - DISPLAY=${DISPLAY}
    hostname: android-emulator
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
    devices:
      - "/dev/kvm:/dev/kvm"
    ports:
      - "5037:5037"
      - "5554:5554"
      - "5555:5555"
      - "5900:5900"

  flutter-dev:
    build:
      context: ./images/flutter-dev
      dockerfile: Dockerfile
      args:
        - ANDROID_API_LEVEL=${ANDROID_API_LEVEL}
        - FLUTTER_VERSION=${FLUTTER_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - android-emulator
    image: ${COMPOSE_PROJECT_NAME}/flutter-dev:${FLUTTER_TAG}

  laravel-dev:
      build:
        context: ./images/laravel-dev
        dockerfile: Dockerfile
        args:
          - DEVELOPSY_BASE_TAG=${DEVELOPSY_BASE_TAG}
          - http_proxy
          - https_proxy
          - no_proxy
      depends_on:
        - base
      image: ${COMPOSE_PROJECT_NAME}/laravel-dev:base-1.0

  vue:
    build:
      context: ./images/vue
      dockerfile: Dockerfile
      args:
        - DEVELOPSY_BASE_TAG=${DEVELOPSY_BASE_TAG}
        - NVM_VERSION=${NVM_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - base
    image: ${COMPOSE_PROJECT_NAME}/vue:ubuntu

  vue-alpine:
    build:
      context: ./images/vue
      dockerfile: Dockerfile.alpine
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - base-alpine
    image: ${COMPOSE_PROJECT_NAME}/vue:alpine

  java-dev:
    build:
      context: ./images/java-dev
      dockerfile: Dockerfile
      args:
        - DEVELOPSY_BASE_TAG=${DEVELOPSY_BASE_TAG}
        - JDK_VERSION=${JDK_VERSION}
        - MAVEN_VERSION=${MAVEN_VERSION}
        - GRADLE_VERSION=${GRADLE_VERSION}
        - http_proxy
        - https_proxy
        - no_proxy
    depends_on:
      - base
    image: ${COMPOSE_PROJECT_NAME}/java-dev:1.0-${UBUNTU_RELEASE}
